# Generated by Django 3.2.7 on 2021-09-05 10:48

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.get_member_image_uploadpath, verbose_name='Image')),
                ('position', models.CharField(max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Profile Link')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter Profile Link')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn Profile Link')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.get_testimonial_image_uploadpath, verbose_name='Image')),
                ('organization', models.CharField(max_length=100, verbose_name='Reviewer Organization Name')),
                ('testimonial', models.TextField()),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
